import { spawn } from 'node:child_process';
import { once } from 'node:events';
import fs from 'node:fs';
import http from 'node:http';
import puppeteer from 'puppeteer-core';

const port = Number(process.env.PORT || 4173);
const url = `http://127.0.0.1:${port}/`;

function chromeExecutable() {
  const candidates = [
    process.env.CHROME_PATH,
    '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    '/Applications/Chromium.app/Contents/MacOS/Chromium',
    '/usr/bin/google-chrome',
    '/usr/bin/chromium',
    '/usr/bin/chromium-browser',
  ].filter(Boolean);

  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) {
      return candidate;
    }
  }

  throw new Error('Chrome/Chromium executable not found. Set CHROME_PATH to run the smoke test.');
}

function get(targetUrl) {
  return new Promise((resolve, reject) => {
    const req = http.get(targetUrl, (res) => {
      res.resume();
      resolve(res.statusCode || 0);
    });
    req.on('error', reject);
    req.setTimeout(500, () => {
      req.destroy(new Error('timeout'));
    });
  });
}

async function waitForServer(targetUrl) {
  const started = Date.now();
  while (Date.now() - started < 15_000) {
    try {
      const status = await get(targetUrl);
      if (status >= 200 && status < 500) {
        return;
      }
    } catch {
      // keep waiting
    }
    await new Promise((resolve) => setTimeout(resolve, 250));
  }
  throw new Error(`Timed out waiting for ${targetUrl}`);
}

const server = spawn('npx', ['vite', 'preview', '--host', '127.0.0.1', '--port', String(port)], {
  stdio: ['ignore', 'pipe', 'pipe'],
});

let browser;
try {
  await waitForServer(url);
  browser = await puppeteer.launch({
    executablePath: chromeExecutable(),
    headless: 'new',
    args: ['--no-sandbox', '--disable-gpu'],
  });

  const page = await browser.newPage();
  const messages = [];
  page.on('console', (message) => {
    if (message.type() !== 'error') {
      return;
    }
    const text = message.text();
    // External analytics/fonts/CDNs can fail in headless/offline environments;
    // the smoke test only cares about app/runtime errors.
    if (text.includes('Failed to load resource')) {
      return;
    }
    messages.push(text);
  });
  page.on('pageerror', (error) => messages.push(error.message));

  await page.goto(url, { waitUntil: 'networkidle2', timeout: 30_000 });
  await page.waitForSelector('#generateFormCalendar', { timeout: 15_000 });

  await page.evaluate(() => {
    $('#inputTitle').val('Smoke Test Event');
    $('#inputDetails').val('Generated by smoke test');
    $('#inputVenue').val('Singapore');
    $('#inputStartDate2').val('May 3, 2026');
    $('#inputStartTime2').val('6:00 PM');
    $('#inputEndDate2').val('May 3, 2026');
    $('#inputEndTime2').val('7:00 PM');
    $('#timezones').selectpicker('val', 'Asia/Singapore');
    $('#generateFormCalendar').trigger('change');
  });

  const result = await page.evaluate(() => ({
    direct: $('#outputDirectLink').val(),
    google: $('#outputGCalLink').val(),
    timezoneCount: $('#timezones option').length,
  }));

  if (messages.length > 0) {
    throw new Error(`Browser console/page errors:\n${messages.join('\n')}`);
  }
  if (!result.direct.includes('Smoke%20Test%20Event') && !result.direct.includes('Smoke+Test+Event')) {
    throw new Error(`Direct link was not generated correctly: ${result.direct}`);
  }
  if (!result.google.startsWith('https://www.google.com/calendar/render')) {
    throw new Error(`Google Calendar link was not generated correctly: ${result.google}`);
  }
  if (result.timezoneCount < 100) {
    throw new Error(`Timezone select was not populated correctly: ${result.timezoneCount}`);
  }

  console.log('Smoke test passed');
} finally {
  if (browser) {
    await browser.close();
  }
  server.kill('SIGTERM');
  await once(server, 'exit').catch(() => {});
}
